name: GitHub Pages

on:
  schedule:
  - cron: "0 0 * * 0"

jobs:
    update-gh-page:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Doxygen Action
          uses: mattnotmitt/doxygen-action@v1.3.1
          with:
            enable-latex: true
            #working-directory: ${{ github.workspace }}
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./docs/html/
              
        
